# Setup
title:        Esther Kerley
tagline:      Student, Nerd, Etc...
baseurl:      ""
commonurl:    "EstherKerley.io"
paginate:     1

# About/contact
author:
  avatar:     /assets/img/personal/avatar.jpg
  name:       Esther Kerley
  email:      Esther@Kerley.io
  url:        http://Esther.kerley.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-asciinema

#Others
markdown: kramdown